### ISSUE TITLE
Dashboards are not loading on grafana start

### ISSUE THREAD

**Issue by huygaa11** [cncf/devstats-example#4]
When I deploy Beam on devstats, the dashboards under `grafana/dashboards/beam` are not loaded by default and I am currently adding them manually using the Grafana UI. Should they load by default? If so, did I mess up my config in [Beam](https://github.com/huygaa11/devstats-example)? Thanks

**Comment by lukaszgryglicki** [comment]
No, they're not added by default, please see:
- [last step "Configure Grafana" on devstats-example install file](https://github.com/cncf/devstats-example/blob/master/INSTALL_UBUNTU18.md)
- [eventually, more complex setup for multiple projects in devstats on the original repo - last few steps](https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md)

**Comment by huygaa11** [comment]
ah, I missed the put all charts. Thanks.

**Comment by lukaszgryglicki** [comment]
No problem.
