### ISSUE TITLE
replacer command not found - Linux installation

### ISSUE THREAD

**Issue by ericKlawitter** [cncf/devstats-example#5]
Hello, 

When following the instructions to install on Linux, I get an error with the following output when running the deploy script: 

`DevStats binaries copied.
devstats was not running
/bin/cronctl.sh: line 16: replacer: command not found`

I see the `replacer` binary in my devstats-example/ and devstats/ directories after running `make`, so I'm not sure if the issue is with this script being in /bin/ or what, but after copying the binary to that location I still saw errors and thought it would be better to ask here instead of trying to hack around it. 

This happens when running the deploy script from both devstats/ and devstats-example.

**Comment by lukaszgryglicki** [comment]
Seems like some PATH issue or something like that. What happens when you type `devstats` from your home directory? It should be accessible from all directories. Is your `$GOPATH/bin` added to your `$PATH`?

**Comment by ericKlawitter** [comment]
Thanks for the quick reply - it was an issue with my $PATH and I was able to deploy successfully once that was fixed! 

One more question - when I run the devel/put_all_charts.sh script to generate my dashboards, I get the following error: 

> Error: 'no such table: dashboard'
Stacktrace:
...
	/devstats/cmd/sqlitedb/sqlitedb.go:268
main.main()
	/devstats/cmd/sqlitedb/sqlitedb.go:415
...

Is this an issue, or did I miss something when setting up my Postgres instance?

**Comment by lukaszgryglicki** [comment]
Put all charts attempts to modify Grafana SQLite database. You can try to see what that database contains via:
- First install SQLite client, something like `apt install sqlite3` or maybe `apt install sqlite-client`.
- Then check the SQLite database structure, something like: `sqlite3 /var/lib/grafana.projname/grafana.db`.

Maybe you don't have a database structure yet. Make sure you followed the last step from the installation doc, eventually try to import one dashboard (for example home dashboard `dashboards.json`) using Grafana UI.

**Comment by ericKlawitter** [comment]
Thanks, I think this is looking good.
