### ISSUE TITLE
Update scripts so there is a single location where project is hard coded

### ISSUE THREAD

**Issue by jlewi** [cncf/devstats-example#6]
The instructions: https://github.com/cncf/devstats-example/blob/master/SETUP_OTHER_PROJECT.md

Currently have the project name hard coded in a bunch of scripts.

It would be helpful if there was a single location that could be updated to set variables like `all`.

**Comment by lukaszgryglicki** [comment]
I will add some shell script that will auto update this, so you will have to clone this repo and then run something like `./set_project_name.sh lowercasename ActualProjectName`.

**Comment by lukaszgryglicki** [comment]
Script [implemented](https://github.com/cncf/devstats-example/blob/master/set_project_name.sh). Details how to setup own project [here](https://github.com/cncf/devstats-example/blob/master/SETUP_OTHER_PROJECT.md) (linked from the main [README](https://github.com/cncf/devstats-example/blob/master/README.md)).
