### ISSUE TITLE
init_database fails if try to rerun with drop database because gha_admin already exists

### ISSUE THREAD

**Issue by jlewi** [cncf/devstats-example#8]
I ran init_database.sh and it failed because I didn't have PG_PASS_ROLE defined.

So then I reran it with drop enabled

```
PG_PASS=${PG_PASS} PG_PASS_RO=${PG_PASS} PG_PASS_TEAM=kubeflow UDROP=1 LDROP=1 ./devel/init_database.sh
```

But this hits an error because the `gha_admin` user can't be deleted because that's the current user.

As a result init_database.sh hits an error when trying to recreate the `gha_admin` user here and exits
https://github.com/cncf/devstats-example/blob/1656f07c84337652deeeeaa145672973b2d142ab/devel/init_database.sh#L50

**Comment by jlewi** [comment]
I think this might have been user error on my part.

I was setting environment variable PG_DB to be my project database. As a result, it was my default database which might have caused the problem. Whereas if we use the database `gha` as the default we should be able to drop the project database just fine.

Its also not clear that I should even be using this script.

**Comment by lukaszgryglicki** [comment]
All you need to do. should just be following steps from zSETUP_OTHER_PROJECT.md. I remember that everything worked OK last time I've checked it. `devstats` is now using updated scripts that use single shell script encapsulating all DB operations `devel/db.sh`. I will update this repo too while splitting code from CNCF deployment details. I've also updated all stuff to disallow diverging. There probably will be 3 repos: `devstats` (with just a code), `devstats-cncf` (deployment for CNCF projects), `devstats-example` (simplest possible deployment for a single project aimed to allow people porting `devstats` to their own project(s)). There may also be `devstats-kubernetes` repo with a `devstats` deployment for Kubernetes. I just need some time.
